---
version: "3"
services:
  node:
    image: sreekanthpv12/nodebackend
          #build:
          # context: .
          # dockerfile: Dockerfile.node
    ports:
      - 8000:8000
    network_mode: host
  react:
    image: sreekanthpv12/reactwebapp:latest 
    # build:
    #    context: .
    #    dockerfile: Dockerfile
    ports:
      - 9000:9000
    network_mode: host
  mongodb:
    image: mongo:3
    ports:
      - 27017:27017
    network_mode: host
