mongodb-deployment:
  replicas: 1
  image: mongo:3
  containerPort: 27017

nodebackend-deployment:
  replicas: 1
  image: sreekanthpv12/nodebackend:v5
  containerPort: 8000

reactwebapp-deployment:
  replicas: 1
  image: sreekanthpv12/reactwebapp:v3
  containerPort: 9000

mongodb-service:
  port: 27017
  targetPort: 27017

nodebackend-service:
  port: 8000
  targetPort: 8000

reactwebapp-service:
  port: 9000
  targetPort: 9000

